server:
  servlet:
    context-path: /api
  port: 8182
  error:
    include-message: always

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/latihandocker
    username: postgres
    password: rahasia
    pool-size: 30
    type: com.zaxxer.hikari.HikariDataSource

  flyway:
    baselineOnMigrate: true
    check-location: true
    locations: classpath:db/migration
    schemas: public
    enabled: true